baseURL = "https://compiled.ctl.columbia.edu/"
copyright = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "CompilED: And Often Interpreted"
SectionPagesMenu = "main"
theme = "ctl-compiled"

[taxonomies]
    tag = "tags"
    author = "authors"

[params]
    description = "CompilED is a collection of posts by the software developers at Center for Teaching and Learning (CTL) at Columbia University. These views are rooted in our professional and personal experiences developing educational technology. These posts are directed at software developers and architects, UX/UI designers, and media/video producers of all flavors, but everyone is welcome."
    keywords = "edtech, educational technology, software development"
    shortTitle = "CompilED"
